version: "3"
services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quizzz
